### ISSUE TITLE
无法加载

### ISSUE THREAD

**Issue by anieyyds** [SlimefunGuguProject/FluffyMachines#55]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/FluffyMachines/issues)，且没有找到相同的问题

### 问题描述

装了GuizhanLibPlugin-Build 41 (git cc6e320)和FluffyMachines-Build 27 (git c392d1b)，但是无法加载蓬松科技，用的是mohist-1.16.5-131核心，Slimefun-eabaa21-Beta。以下是服务器显示的信息
[14:26:51 INFO]: [Slimefun] Enabling Slimefun veabaa21-Beta
[14:26:51 WARN]: [Slimefun] ====================================================
[14:26:51 WARN]: [Slimefun]  Slimefun 在 Paper 上会工作地更好 
[14:26:51 WARN]: [Slimefun]  推荐你使用 Paper 运行Slimefun 
[14:26:51 WARN]: [Slimefun]   
[14:26:51 WARN]: [Slimefun]  Paper 能提供显著性能优化, 且更安全,
[14:26:51 WARN]: [Slimefun]  以及 Bug 修复和部分新特性
[14:26:51 WARN]: [Slimefun]  提升服主的服务器体验.
[14:26:51 WARN]: [Slimefun]   
[14:26:51 WARN]: [Slimefun]  Paper 内置了 Timings v2. 相比 v1 版本
[14:26:51 WARN]: [Slimefun]  能够更显著地诊断服务器卡顿原因.
[14:26:51 WARN]: [Slimefun]   
[14:26:51 WARN]: [Slimefun]  你原有的插件在更换后大部分都能正常使用.
[14:26:51 WARN]: [Slimefun]  如果遇到问题, Paper 社区很乐意帮助你解决你的问题.
[14:26:51 WARN]: [Slimefun]   
[14:26:51 WARN]: [Slimefun]  加入 Paper 社区 @ https://papermc.io
[14:26:51 WARN]: [Slimefun] ====================================================
[14:26:51 INFO]: [Slimefun] 正在创建文件夹...
[14:26:51 INFO]: [Slimefun] 正在加载数据库...
[14:26:51 INFO]: SlimefunHikariPool - Starting...
[14:26:51 INFO]: SlimefunHikariPool - Added connection org.sqlite.jdbc4.JDBC4Connection@5e22ace7
[14:26:51 INFO]: SlimefunHikariPool - Start completed.
[14:26:51 INFO]: [Slimefun] 已启用延时写入功能
[14:26:51 INFO]: SlimefunHikariPool - Starting...
[14:26:51 INFO]: SlimefunHikariPool - Added connection org.sqlite.jdbc4.JDBC4Connection@7cabe115
[14:26:51 INFO]: SlimefunHikariPool - Start completed.
[14:26:51 INFO]: [Slimefun] 正在加载语言文件...
[14:26:52 INFO]: [Slimefun] Loaded language "zh-CN"
[14:26:52 INFO]: [Slimefun] Available languages: en, de, fr, it, es, ru, pl, uk, sv, nl, da, cs, ro, bg, pt, pt-BR, hu, lv, sk, vi, id, zh-CN, zh-TW, ja, ko, he, ar, tr, fa, th, tl
[14:26:52 INFO]: [Slimefun] 加载矿物资源...
[14:26:53 INFO]: [Slimefun] 加载自定义标签...
[14:26:53 INFO]: [Slimefun] 加载物品...
[14:26:54 INFO]: [Slimefun] 加载研究项目...
[14:26:54 INFO]: [Slimefun] 加载 Wiki 页面...
[14:26:54 INFO]: [Slimefun] 加载了 Slimefun 中 485 个物品的 Wiki 页面
[14:26:54 INFO]: [Slimefun] 正在注册监听器...
[14:26:55 WARN]: [Slimefun] 无法接入 Vault. 你必须先安装 Vault!
[14:26:55 INFO]: [Slimefun] 正在加载第三方插件支持...
[14:26:55 INFO]: [Slimefun] Slimefun 完成加载, 耗时 3.97s
[14:26:55 INFO]: [GuizhanLibPlugin] Enabling GuizhanLibPlugin vBuild 41 (git cc6e320)
[14:26:55 INFO]: [GuizhanLibPlugin] Finding language file for Minecraft version 1.16
[14:26:55 INFO]: [GuizhanLibPlugin] Loading language file for Minecraft version 1.16
[14:26:55 INFO]: [GuizhanLibPlugin] Loaded language file for Minecraft version 1.16
[14:26:55 INFO]: [FluffyMachines] Enabling FluffyMachines vBuild 27 (git c392d1b)
[14:26:55 ERROR]: Error occurred while enabling FluffyMachines vBuild 27 (git c392d1b) (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.RecipeChoice.clone()" because "ingredient" is null
        at org.bukkit.inventory.ShapelessRecipe.getChoiceList(ShapelessRecipe.java:282) ~[forge:?]
        at io.ncbpfluffybear.fluffymachines.FluffyMachines.onEnable(FluffyMachines.java:95) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:502) ~[forge:7e29f765-296df566-9fb885e8]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:414) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:427) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:347) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:227) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:768) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:267) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[14:26:55 INFO]: [FluffyMachines] Disabling FluffyMachines vBuild 27 (git c392d1b)
[14:26:55 INFO]: Server permissions file permissions.yml is empty, ignoring it
[14:26:55 INFO]: Preparing start region for dimension minecraft:overworld
[14:26:56 INFO]: Preparing spawn area: 0%
[14:26:57 INFO]: Preparing spawn area: 70%
[14:26:57 INFO]: Time elapsed: 2,333 ms
[14:26:57 INFO]: Done (6.834s)! For help, type "help"
[14:26:57 INFO]: [GuizhanLibPlugin] Loaded language pack!
[14:26:57 INFO]: [GuizhanLibPlugin] Initializing universal updater task...
[14:26:57 INFO]: [GuizhanLibPlugin] Found 2 updater tasks.
[14:26:57 INFO]: [GuizhanLibPlugin] Running task 1 (GuizhanLibPlugin)...
[14:26:57 INFO]: [GuizhanLibPlugin] Running task 2 (FluffyMachines)...
[14:26:57 ERROR]: [GuizhanLibPlugin] Updater task (FluffyMachines) failed!
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:525) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:229) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:225) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:170) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:139) ~[forge:?]
        at net.guizhanss.guizhanlib.updater.AbstractGuizhanBuildsUpdater.start(AbstractGuizhanBuildsUpdater.java:219) ~[?:?]
        at net.guizhanss.guizhanlibplugin.updater.UniversalUpdaterTask.runTask(UniversalUpdaterTask.java:84) ~[?:?]
        at net.guizhanss.guizhanlibplugin.updater.UniversalUpdaterTask.run(UniversalUpdaterTask.java:42) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:90) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[forge:?]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:20) ~[forge:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[14:26:57 INFO]: [Slimefun] Now running MetricsModule build #29
[14:26:57 INFO]: [Slimefun] with a total of 14/19 chart(s)!
[14:26:57 INFO]: [Slimefun] Metrics build #29 started.
[14:26:57 INFO]: [Slimefun] Collecting Snapshots of all Recipes...
[14:26:57 INFO]: [Slimefun] Found 2,048 Recipes!
[14:26:58 INFO]: 
[14:26:58 INFO]: ######################### - Slimefun veabaa21-Beta - #########################
[14:26:58 INFO]: 
[14:26:58 INFO]: 成功加载了 555 个物品和 258 个研究
[14:26:58 INFO]: ( 555 物品来自本体, 0 个物品来自 2 扩展 )
[14:26:58 INFO]: 
[14:26:58 INFO]: 
[14:26:58 INFO]:  - 源码:      https://github.com/StarWishsama/Slimefun4
[14:26:58 INFO]:  - Bug 反馈:  https://github.com/StarWishsama/Slimefun4/issues
[14:26:58 INFO]: 
[14:26:58 INFO]: Loading Protection Modules...
[14:26:58 INFO]: This may happen more than once.
[14:26:59 INFO]: [Slimefun] Slimefun 已是最新版本。
[14:27:01 INFO]: [GuizhanLibPlugin] GuizhanLibPlugin is up to date.
[14:27:12 WARN]: [Slimefun] 检测到没有安装 SlimeGlue (粘液胶), 你将缺失对一些插件的额外保护检查!
[14:27:12 WARN]: [Slimefun] 下载: https://github.com/Xzavier0722/SlimeGlue

### 复现步骤

必现

### 预期行为

正常运行，因为之前装其他粘液插件都能运行，所以把其他插件都删了，但还是不行

### 服务端软件

其他 (请在问题描述里写明)

### Minecraft 版本

Java 1.16.5

### Slimefun版本

Slimefun-eabaa21-Beta

### 插件版本

FluffyMachines-Build 27 (git c392d1b)

**Comment by ybw0014** [comment]
不对混合段提供支持
